name: Cypress-e2e
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run cypress
        uses: cypress-io/github-action@v6
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: Cypress/cypress/videos
      - name: Upload Cypress screenshots (optional)
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
