name: Cypress-e2e
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run cypress
        uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v2
        if: always()
        with:
            name: playwright-report
            path: Cypress/cypress/videos
            retention-days: 30
